
spring:
   jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
      
   datasource:
        url: jdbc:mysql://spinxodb.c6ylyk9lhaqa.ap-south-1.rds.amazonaws.com:3306/consuldb
        username: spinxo
        password: 123456789
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 10
        max-idle: 5
        min-idle: 1
        testWhileIdle: true
        test-on-borrow: true
        validationQuery: SELECT 1
        timeBetweenEvictionRunsMillis: 5000
        min-evictable-idle-time-millis: 60000
 
#config:
# oauth2:
#  accessTokenUri: http://localhost:8080/auth/oauth/token
  
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    

